// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sueyqpyrafdcohfgnqpq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1ZXlxcHlyYWZkY29oZmducXBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNzYxNjYsImV4cCI6MjA2ODg1MjE2Nn0.kI5IdxzSvTQ2YuBv52qYMk9Ve0e51nzb3FjE5apq-qk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});